name: Test
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.4"
          - head
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake compile test
